### ISSUE TITLE
PyPI Release?

### ISSUE THREAD

**Issue by jakirkham** [pypa/pkg_resources#12]
I may be misunderstanding the purpose of this, but this looks to me like the breaking out of `pkg_resources` from `setuptools` and then potentially vendorizing the dependency in `setuptools`. Is that correct?

If at least the first part is correct, would it be possible to get a PyPI package for this at some point? I can see a lot of value in being able to use this independently of `setuptools`.

**Comment by jaraco** [comment]
That's the plan at some point. However, it's not really viable currently, as setuptools cannot vendor pkg_resources and can't depend on it, so it would effectively create a fork. The plan is to first get Setuptools to a place where it no longer has to install or upgrade itself, at which point it may become viable to split out this package. For now, it's just a holding place.
