### ISSUE TITLE
pkg_resources.safe_name() is not PEP 503 complient

### ISSUE THREAD

**Issue by StephanErb** [pypa/pkg_resources#13]
[PEP 503](https://www.python.org/dev/peps/pep-0503/#normalized-names) states that:

> [T]he only valid characters in a name are the ASCII alphabet, ASCII numbers, `.`, `-`, and `_`. 
    The name should be lowercased with all runs of the characters `.`, `-`, or `_` replaced with a 
    single `-` character. 

This is implemented differently in [`pkg_resources.safe_name()`](https://github.com/pypa/pkg_resources/blob/b49119ba67cec5892e5c5c7e39b6b83d0cfb1664/pkg_resources/__init__.py#L1416-L1421). The `.` (dot) should be replaced by `-` (hyphen) but isn't. This is causing unexpected behaviour in projects such as pip (e.g. https://github.com/pypa/pip/issues/5021)

There is a little room for interpretation here, as [PEP 426](https://www.python.org/dev/peps/pep-0426/#name) does not require `.` to be replaced by `-`. However [`packaging.utils.canonicalize_name` ](https://github.com/pypa/packaging/blob/878a8c848198d0f6d355c3fa6dc9a474048788cd/packaging/utils.py#L14-L16) implements this by replacing `.` with `-` as well. 

 I therefore believe pkg_resources should to do the same.

**Comment by benoit-pierre** [comment]
Until pkg_resources if effectively split from setuptools, the right place to fill a bug about it is still [there](https://github.com/pypa/setuptools).

**Comment by StephanErb** [comment]
Ah, this explains why it is so quiet over here. Thanks :)

**Comment by StephanErb** [comment]
Before anybody wonders: I just decided not to file the issue over at setuptools. PEP 503 is aimed for PyPI and friends. Changing the behaviour in setuptools would break too many things.

**Comment by pradyunsg** [comment]
@StephanErb pypa/warehouse then?

**Comment by pradyunsg** [comment]
Nvm me.
