### ISSUE TITLE
Point people to setuptools/pkg_resources

### ISSUE THREAD

**Issue by cjerdonek** [pypa/pkg_resources#17]
I think it would be helpful to point people to [`setuptools/pkg_resources`](https://github.com/pypa/setuptools/tree/master/pkg_resources) if they find issues in `pkg_resources`, so people understand that's where the "source of truth" is and where the code is being maintained. This info can go e.g. in this project's README. The README can also say something like that this project contains an older, unmaintained version.

**Comment by jaraco** [comment]
Good idea. Since this effort is abandoned, I'll be removing the code. I'll keep this request in consideration and if there's a good way to give users guidance, I'll do that.
